INSERT INTO rivers (id, name) VALUES (1, 'Donau')
INSERT INTO rivers (id, name) VALUES (2, 'Mürz')
INSERT INTO rivers (id, name) VALUES (3, 'Main')

INSERT INTO locations (id, name, river_id) VALUES (1, 'Vienna', 1)
INSERT INTO locations (id, name, river_id) VALUES (2, 'St. Pölten', 1)
INSERT INTO locations (id, name, river_id) VALUES (3, 'St. Pölten', 2)

INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (1, 100, NOW() - INTERVAL 13 MONTH, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (2, 100, NOW() - INTERVAL 12 MONTH, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (4, 100, NOW() - INTERVAL 11 MONTH, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (5, 100, NOW() - INTERVAL 10 MONTH, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (6, 100, NOW() - INTERVAL 9 MONTH, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (7, 100, NOW() - INTERVAL 8 MONTH, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (8, 100, NOW() - INTERVAL 7 MONTH, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (9, 100, NOW() - INTERVAL 6 MONTH, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (10, 100, NOW() - INTERVAL 5 MONTH, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (11, 100, NOW() - INTERVAL 4 MONTH, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (12, 100, NOW() - INTERVAL 3 MONTH, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (13, 100, NOW() - INTERVAL 2 MONTH, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (14, 100, NOW() - INTERVAL 1 MONTH, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (15, 100, NOW() - INTERVAL 24 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (16, 100, NOW() - INTERVAL 23 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (17, 100, NOW() - INTERVAL 22 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (18, 100, NOW() - INTERVAL 21 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (19, 100, NOW() - INTERVAL 20 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (20, 100, NOW() - INTERVAL 19 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (21, 100, NOW() - INTERVAL 18 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (22, 100, NOW() - INTERVAL 17 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (23, 100, NOW() - INTERVAL 16 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (24, 100, NOW() - INTERVAL 15 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (25, 100, NOW() - INTERVAL 14 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (26, 100, NOW() - INTERVAL 13 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (27, 80, NOW() - INTERVAL 12 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (28, 65, NOW() - INTERVAL 11 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (29, 45, NOW() - INTERVAL 10 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (30, 20, NOW() - INTERVAL 9 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (31, 20, NOW() - INTERVAL 8 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (32, 88, NOW() - INTERVAL 7 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (33, 12, NOW() - INTERVAL 6 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (34, 123, NOW() - INTERVAL 5 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (35, 31, NOW() - INTERVAL 4 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (36, 38, NOW() - INTERVAL 3 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (37, 55, NOW() - INTERVAL 2 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (38, 55, NOW() - INTERVAL 1 HOUR, 1)
INSERT INTO water_levels (id, level, timestamp, location_id) VALUES (39, 100, NOW(), 1)
